name: test ci
run-name: test run name
on:
  push:
    branches:
      - master
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: 步骤1
        run: ls -lh
      - name: 步骤2
        run: |
          pwd
          date
      - name: 步骤3：检出代码
        uses: actions/checkout@v4
      - name: 步骤3
        run: |
          ls -lh
          date
  job2:
    needs: [job1]
    runs-on: windows-latest
    steps:
      - name: job2步骤1
        run: git version
